### ISSUE TITLE
[bug]: Segmentation fault when calling ast_media_cache_init

### ISSUE THREAD

**Issue by almazka** [asterisk/asterisk#229]
### Severity

Critical

### Versions

18.10.1

### Components/Modules

media_cache.c

### Operating Environment

Linux 3.10.0-1062.18.1.el7.x86_64 x86_64

### Frequency of Occurrence

Occasional

### Issue Description

Asterisk was automatically reloaded when calling the function ast_media_cache_init()
Segmentation fault. Program terminated with signal 11,

### Relevant log output

```shell
!@!@!@! info.txt !@!@!@!

Asterisk 18.19.0 built by root @ localhost.localdomain on a x86_64 running Linux on 2023-08-04 09:01:04 UTC

System started: 1970-01-01 03:00:00
Last reload: 1970-01-01 03:00:00

Build options = BUILD_NATIVE, OPTIONAL_API

tps_singletons - Cannot access memory at address 0x30
TaskProcessors not found

bridges - Cannot access memory at address 0x28
Bridges not found

channels - Cannot access memory at address 0x30
Channels not found

Unable to retrieve channel summary


















!@!@!@! full.txt !@!@!@!

$3 = {si_signo = 11, si_errno = 0, si_code = 1, _sifields = {_pad = {56, 0, 0, 0, -964477488, -26023, -1446384359, -1, 0 <repeats 20 times>}, _kill = {si_pid = 56, si_uid = 0}, _timer = {si_tid = 56, si_overrun = 0, si_sigval = {sival_int = 0, sival_ptr = 0x0}}, _rt = {si_pid = 56, si_uid = 0, si_sigval = {sival_int = 0, sival_ptr = 0x0}}, _sigchld = {si_pid = 56, si_uid = 0, si_status = 0, si_utime = -4142399268688232448, si_stime = -6212173515055981991}, _sigfault = {si_addr = 0x38}, _sigpoll = {si_band = 56, si_fd = 0}}}
Signal        Stop	Print	Pass to program	Description
SIGSEGV       Yes	Yes	Yes		Segmentation fault
Thread 28 (LWP 371):
#0  0x0000000000461ee5 in internal_ao2_traverse (self=0x7fc5ac047d00, cb_fn=<optimized out>, arg=<optimized out>, line=0, func=0x7074b3 <Address 0x7074b3 out of bounds>, file=0x646d16 "astobj2_container.c", tag=0x0, type=AO2_CALLBACK_DEFAULT, data=0x0, flags=OBJ_NOLOCK) at astobj2_container.c:408
        ret = <optimized out>
        cb_default = 0x0
        node = <optimized out>
        traversal_state = <optimized out>
        orig_lock = <optimized out>
#1  0x0000000000462147 in internal_ao2_traverse (self=0x7fc58804d0d0, flags=2282019424, cb_fn=<optimized out>, arg=0x7fc58804da60, data=0x7fc58804d0d0, tag=0x9f7320 "", file=0x728ff0 <Address 0x728ff0 out of bounds>, line=5304355, func=0x728c19 <Address 0x728c19 out of bounds>, type=AO2_CALLBACK_WITH_DATA) at astobj2_container.c:318
        ret = 0x518bfd <load_asterisk_conf+2301>
        cb_withdata = 0x7fc58804d1b4
        node = 0x708284
        traversal_state = 0x7fc58804d1b4
        orig_lock = AO2_LOCK_REQ_MUTEX
        multi_container = 0x7074b3
        multi_iterator = 0x7fc608b2e9b0
#2  0x0000000000462531 in internal_ao2_traverse (self=0xa25620, flags=OBJ_SEARCH_NONE, cb_fn=0x462147 <internal_ao2_traverse+551>, arg=0x7fc608b2ea20, tag=0x462147 <internal_ao2_traverse+551> "205300H211303017205376376377377I213E", file=0x7fc5ac047d60 "`274", line=-1408983440, func=0x7fc5ac047df0 "255", 'ޭ' <repeats 65 times>, "336306177", type=AO2_CALLBACK_DEFAULT, data=0x0) at astobj2_container.c:318
        ret = 0x0
        cb_default = 0x7fc58804d0d0
        node = <optimized out>
        traversal_state = 0x462531 <internal_ao2_traverse+241>
        orig_lock = (AO2_LOCK_REQ_RDLOCK | unknown: 32708)
        multi_container = 0xa25620
        multi_iterator = 0x7fc58804da60
#3  0x000000000050f023 in media_cache_item_populate_from_astdb (hash=0x7fc5ac04a350 "p242004254305177", uri=0x7fc608b2ea90 "`252004254305177") at media_cache.c:428
        bucket_file = 0x728c19
        db_tree = 0x7fc5ac047d28
        db_entry = 0x7fc5ac047d60
        st = {st_dev = 7506969, st_ino = 140486971266640, st_nlink = 140486971274512, st_mode = 2885986936, st_uid = 32709, st_gid = 2885986912, __pad0 = 32709, st_rdev = 6632105, st_size = 140488775110217, st_blksize = 140486971273328, st_blocks = 140486971274512, st_atim = {tv_sec = 6597063, tv_nsec = 0}, st_mtim = {tv_sec = 140486971271760, tv_nsec = 140488526195488}, st_ctim = {tv_sec = 0, tv_nsec = 512000}, __unused = {6632105, 140488526195520, 53986344}}
#4  media_cache_populate_from_astdb () at media_cache.c:450
        db_entry = 0x7fc5ac047df0
        db_tree = 0x64a9c7 <__PRETTY_FUNCTION__.20910+23>
#5  ast_media_cache_init () at media_cache.c:685
        __PRETTY_FUNCTION__ = "ast_media_cache_init"
#6  0x00007fc5ac04aa50 in ?? ()
No symbol table info available.
#7  0x00007fc608b2eb90 in ?? ()
No symbol table info available.








!@!@!@! brief.txt !@!@!@!
Thread 28 (LWP 371):
#0  0x0000000000461ee5 in internal_ao2_traverse (self=0x7fc5ac047d00, cb_fn=<optimized out>, arg=<optimized out>, line=0, func=0x7074b3 <Address 0x7074b3 out of bounds>, file=0x646d16 "astobj2_container.c", tag=0x0, type=AO2_CALLBACK_DEFAULT, data=0x0, flags=OBJ_NOLOCK) at astobj2_container.c:408
#1  0x0000000000462147 in internal_ao2_traverse (self=0x7fc58804d0d0, flags=2282019424, cb_fn=<optimized out>, arg=0x7fc58804da60, data=0x7fc58804d0d0, tag=0x9f7320 "", file=0x728ff0 <Address 0x728ff0 out of bounds>, line=5304355, func=0x728c19 <Address 0x728c19 out of bounds>, type=AO2_CALLBACK_WITH_DATA) at astobj2_container.c:318
#2  0x0000000000462531 in internal_ao2_traverse (self=0xa25620, flags=OBJ_SEARCH_NONE, cb_fn=0x462147 <internal_ao2_traverse+551>, arg=0x7fc608b2ea20, tag=0x462147 <internal_ao2_traverse+551> "205300H211303017205376376377377I213E", file=0x7fc5ac047d60 "`274", line=-1408983440, func=0x7fc5ac047df0 "255", 'ޭ' <repeats 65 times>, "336306177", type=AO2_CALLBACK_DEFAULT, data=0x0) at astobj2_container.c:318
#3  0x000000000050f023 in media_cache_item_populate_from_astdb (hash=0x7fc5ac04a350 "p242004254305177", uri=0x7fc608b2ea90 "`252004254305177") at media_cache.c:428
#4  media_cache_populate_from_astdb () at media_cache.c:450
#5  ast_media_cache_init () at media_cache.c:685
#6  0x00007fc5ac04aa50 in ?? ()
#7  0x00007fc608b2eb90 in ?? ()
```

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by jcolp** [comment]
Was Asterisk built with optimization disabled? As well, such things should be attached and not embedded. You also state version "18.10.1" yet your output shows "18.19.0"

**Comment by almazka** [comment]
> Can you clarify what "automatically reloaded" means? How often does this actually occur?

Asterisk crashes with an error and the service restarts. Ie all the calls that were at the time of the fall are torn. This happens from time to time. I can't find any case to reproduce this error
