### ISSUE TITLE
[bug]: Segmentation Fault 

### ISSUE THREAD

**Issue by daninmadison** [asterisk/asterisk#251]
### Severity

Trivial

### Versions

18.17.1

### Components/Modules

pjsip

### Operating Environment

Linux Ubuntu 20

### Frequency of Occurrence

None

### Issue Description

A customer encountered the following segmentation fault.  The only fix I could identify in this section of code was the ABI fix recently added.

### Relevant log output

```shell
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055e7c091ed95 in __ao2_ref (user_data=user_data@entry=0x1, delta=delta@entry=1, tag=tag@entry=0x0, file=file@entry=0x7f773800e012 "res_pjsip_session.c", line=line@entry=3639,
    func=func@entry=0x7f7738011d20 <__PRETTY_FUNCTION__.38105> "ast_sip_dialog_get_session") at astobj2.c:501
501     astobj2.c: No such file or directory.
[Current thread is 1 (Thread 0x7f772c1a1700 (LWP 124120))]
(gdb) bt
#0  0x000055e7c091ed95 in __ao2_ref (user_data=user_data@entry=0x1, delta=delta@entry=1, tag=tag@entry=0x0, file=file@entry=0x7f773800e012 "res_pjsip_session.c", line=line@entry=3639,
    func=func@entry=0x7f7738011d20 <__PRETTY_FUNCTION__.38105> "ast_sip_dialog_get_session") at astobj2.c:501
#1  0x00007f773800a0da in ast_sip_dialog_get_session (dlg=dlg@entry=0x7f777415de48) at res_pjsip_session.c:3639
#2  0x00007f773800d3e7 in session_outgoing_nat_hook (tdata=0x7f773c633ac8, transport=0x7f7754082048) at res_pjsip_session.c:5567
#3  0x00007f773801965d in nat_invoke_hook (obj=<optimized out>, arg=arg@entry=0x7f772c1a0a50, flags=flags@entry=0) at res_pjsip_nat.c:299
#4  0x000055e7c09218c0 in internal_ao2_traverse (self=self@entry=0x7f774014cc18, flags=flags@entry=OBJ_SEARCH_NONE, cb_fn=cb_fn@entry=0x7f7738019640 <nat_invoke_hook>, arg=arg@entry=0x7f772c1a0a50, tag=tag@entry=0x0,
    file=file@entry=0x7f773801b009 "res_pjsip_nat.c", line=<optimized out>, func=<optimized out>, type=AO2_CALLBACK_DEFAULT, data=0x0) at astobj2_container.c:328
#5  0x000055e7c0921d79 in __ao2_callback (c=c@entry=0x7f774014cc18, flags=flags@entry=OBJ_SEARCH_NONE, cb_fn=cb_fn@entry=0x7f7738019640 <nat_invoke_hook>, arg=arg@entry=0x7f772c1a0a50, tag=tag@entry=0x0,
    file=file@entry=0x7f773801b009 "res_pjsip_nat.c", line=470, func=0x7f773801b4b8 <__PRETTY_FUNCTION__.29250> "process_nat") at astobj2_container.c:414
#6  0x00007f7738019ddf in process_nat (tdata=0x7f773c633ac8) at res_pjsip_nat.c:470
#7  nat_on_tx_message (tdata=0x7f773c633ac8) at res_pjsip_nat.c:479
#8  0x00007f777bc6fc66 in endpt_on_tx_msg (endpt=<optimized out>, tdata=0x7f773c633ac8) at ../src/pjsip/sip_endpoint.c:1115
#9  0x00007f777bc77c69 in pjsip_transport_send (tr=0x55e7c1ac7708, tdata=tdata@entry=0x7f773c633ac8, addr=addr@entry=0x7f773c633cb8, addr_len=addr_len@entry=16, token=token@entry=0x7f773c635950,
    cb=cb@entry=0x7f777bc71610 <stateless_send_transport_cb>) at ../src/pjsip/sip_transport.c:935
#10 0x00007f777bc717d9 in stateless_send_transport_cb (token=token@entry=0x7f773c635950, tdata=tdata@entry=0x7f773c633ac8, sent=<optimized out>, sent@entry=-70002) at ../src/pjsip/sip_util.c:1276
#11 0x00007f777bc71b3a in stateless_send_resolver_callback (status=<optimized out>, token=0x7f773c635950, addr=<optimized out>) at ../src/pjsip/sip_util.c:1377
#12 0x00007f77380c3398 in sip_resolve_invoke_user_callback (data=0x7f773c4563c8) at res_pjsip/pjsip_resolver.c:206
#13 0x000055e7c0a6f0e3 in ast_taskprocessor_execute (tps=tps@entry=0x7f775416ebc0) at taskprocessor.c:1302
#14 0x000055e7c0a76d28 in execute_tasks (data=0x7f775416ebc0) at threadpool.c:1352
#15 0x000055e7c0a6f0e3 in ast_taskprocessor_execute (tps=0x55e7c2697720) at taskprocessor.c:1302
#16 0x000055e7c0a7760c in threadpool_execute (pool=0x55e7c269be10) at threadpool.c:367
#17 worker_active (worker=0x7f7770001740) at threadpool.c:1137
#18 worker_start (arg=arg@entry=0x7f7770001740) at threadpool.c:1056
#19 0x000055e7c0a7f868 in dummy_start (data=<optimized out>) at utils.c:1574
#20 0x00007f777b4ba609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#21 0x00007f777b23c133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by jcolp** [comment]
This backtrace is a start, but we need a full set of backtraces including full according to the documentation[1]. We also need an Asterisk log[2] leading up to the crash to better identify the circumstances that lead to the crash. These should be attached to the issue, and not posted inline.

[1] https://docs.asterisk.org/Development/Debugging/Getting-a-Backtrace/?h=backtrace
[2] https://docs.asterisk.org/Operation/Logging/Collecting-Debug-Information/?h=collecting

**Comment by jcolp** [comment]
Actually looking back at history this appears to be https://issues-archive.asterisk.org/ASTERISK-30005 so I'm opening this.

**Comment by pmbobc** [comment]
We also had a similar crash. Following is the log.

```
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/usr/sbin/asterisk -f -vvvg -c'.
Program terminated with signal 11, Segmentation fault.
#0  0x0000000000460c9c in __ao2_ref (user_data=user_data@entry=0x73673b30323a3932, delta=delta@entry=1, tag=tag@entry=0x0, file=file@entry=0x7f8ae2259492 "res_pjsip_session.c", line=line@entry=3647, 
    func=func@entry=0x7f8ae225d140 <__PRETTY_FUNCTION__.36058> "ast_sip_dialog_get_session") at astobj2.c:501
501		struct astobj2 *obj = __INTERNAL_OBJ_CHECK(user_data, file, line, func);
```

We were able to generate a backtrace from the coredump file following (https://docs.asterisk.org/Development/Debugging/Getting-a-Backtrace/)

It generated the following files

```
core-asterisk-2024-03-13T06-55-03Z-brief.txt
core-asterisk-2024-03-13T06-55-03Z-full.txt
core-asterisk-2024-03-13T06-55-03Z-info.txt
core-asterisk-2024-03-13T06-55-03Z-locks.txt
core-asterisk-2024-03-13T06-55-03Z-thread1.txt
```

Please let us know if these are similar crashes, if yes - would sharing these backtraces help? (Which one to share?)

**Comment by jcolp** [comment]
You've only provided a single line so it's impossible to say with certainty if it's similar/the same. You'd have to attach a -brief backtrace file to know for certain.

**Comment by pmbobc** [comment]
Hello,

Please find attachment foe the same

Please let us know if needed any other information

Thanks in advance
[core-asterisk-2024-03-13T06-55-03Z-brief.txt](https://github.com/asterisk/asterisk/files/14610436/core-asterisk-2024-03-13T06-55-03Z-brief.txt)

**Comment by jcolp** [comment]
Yes, that is the same issue as this one already filed.

**Comment by pmbobc** [comment]
Hello,
We have installed unbound and using local DNS, bu the issue still exists. Can we get a patch for this bug?

**Comment by jcolp** [comment]
There is currently no patch written, and I'm not aware of anyone actively working on this issue.

**Comment by pmbobc** [comment]
@jcolp Thank you, we appreciate you taking the time to respond to us. We hope that we'll get a patch soon and there is enough debugging information to do that.
