### ISSUE TITLE
[bug]: Asterisk 18 crash

### ISSUE THREAD

**Issue by nnew2** [asterisk/asterisk#382]
### Severity

Major

### Versions

18.16.0

### Components/Modules

We don't know which component is causing this

### Operating Environment

Debian 11 Bullseye
_Linux foobar 5.10.0-23-cloud-amd64 #1 SMP Debian 5.10.179-1 (2023-05-12) x86_64 GNU/Linux_

Running in Amazon EC2.

### Frequency of Occurrence

Occasional

### Issue Description

Asterisk randomly crashes with segfault.

_Oct 23 09:10:49 foobar kernel: [10089128.440204] asterisk[3785963]: segfault at 7fb8aa51c140 ip 00007fb9b8335ab8 sp 00007fb96782cbd8 error 4 in libc-2.31.so[7fb9b81e6000+159000]_

We have not find a way to replicate this and the **issue is random**. The Asterisk is running between 60-80 peers so it is a somewhat loaded system but there's plenty of resources (CPU, RAM, DISK etc.).

Now we're aware that this is **not the latest Asterisk 18** branch version; we could update the Asterisk but there's a risk that it will take weeks to months before the issue is replicated again, hence the reason I am still creating this report. Hopefully the issue can be found and a fix already is in place, or can be created for a future version.

I have attached backtrace from the core dump.

[core-asterisk-2023-10-23T11-57-06Z-brief.txt](https://github.com/asterisk/asterisk/files/13069913/core-asterisk-2023-10-23T11-57-06Z-brief.txt)
[core-asterisk-2023-10-23T11-57-06Z-full.txt](https://github.com/asterisk/asterisk/files/13069915/core-asterisk-2023-10-23T11-57-06Z-full.txt)
[core-asterisk-2023-10-23T11-57-06Z-info.txt](https://github.com/asterisk/asterisk/files/13069917/core-asterisk-2023-10-23T11-57-06Z-info.txt)
[core-asterisk-2023-10-23T11-57-06Z-locks.txt](https://github.com/asterisk/asterisk/files/13069918/core-asterisk-2023-10-23T11-57-06Z-locks.txt)
[core-asterisk-2023-10-23T11-57-06Z-thread1.txt](https://github.com/asterisk/asterisk/files/13069919/core-asterisk-2023-10-23T11-57-06Z-thread1.txt)

### Relevant log output

```shell
#9  0x000055e3284d1795 in action_status (s=0x7fb96782e440, m=0x7fb96782e940) at manager.c:4961
#10 0x000055e3284c6e82 in process_message (s=s@entry=0x7fb96782e440, m=m@entry=0x7fb96782e940) at manager.c:7100
#11 0x000055e3284ced81 in do_message (s=0x7fb96782e440) at manager.c:7313
#12 session_do (data=0x7fb944001830) at manager.c:7418
#13 0x000055e328464c2d in dummy_start (data=<optimized out>) at utils.c:1574
#14 0x00007fb9b8538ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#15 0x00007fb9b82bfa2f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by jcolp** [comment]
This is crashing due to an AMI action, specifically "Status". We would need to know the contents of the AMI action, as well as the state of the involved channel which can potentially be derived from logs.

**Comment by jcolp** [comment]
Through manually examining the core dump, potentially yes. There are instructions[1] on the docs site for including the raw core dump and Asterisk build files in a tarball. You would then need to make them available somehow, such as Google Drive. If they contain sensitive information they could be provided solely to Sangoma but by doing so you further restrict who can fix/resolve the issue, unless you directly exchange it with someone. There is no time frame or guarantee on fixing.

[1] https://docs.asterisk.org/Development/Debugging/Getting-a-Backtrace/?h=backtrace#reporting-crashes-and-deadlocks

**Comment by nnew2** [comment]
Right now I don't have any other bet to go on but to send it to Sangoma. We do not have the tools nor the knowledge to manipulate and scrub core files.

I will e-mail Sangona with the tarball, and the href to this issue. Moving on from here I'll see what I can find regarding how we use the AMI command Status.
