### ISSUE TITLE
[bug]: Segmentation fault / AGI / Answer

### ISSUE THREAD

**Issue by GotoThor** [asterisk/asterisk#522]
### Severity

Major

### Versions

18.20.0

### Components/Modules

pjsip 2.13.1

### Operating Environment

Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-91-generic x86_64)

### Frequency of Occurrence

Occasional

### Issue Description

I use Asterisk's Dialplan to call an AGI-Script. Sometimes (and randomly) Asterisk crashes when sending "Answer" via AGI to the incoming channel. The same script works fine with Asterisk 16.23.0.

### Relevant log output

```shell
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
--Type <RET> for more, q to quit, c to continue without paging--
Core was generated by `/usr/sbin/asterisk -U voxi -G voxi'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __memcmp_sse2 () at ../sysdeps/x86_64/memcmp.S:50
50      ../sysdeps/x86_64/memcmp.S: No such file or directory.
[Current thread is 1 (Thread 0x7fcf8055c640 (LWP 630931))]
(gdb) bt
#0  __memcmp_sse2 () at ../sysdeps/x86_64/memcmp.S:50
#1  0x00007fcfcf744074 in pj_memcmp (size=14, buf2=<optimized out>, buf1=<optimized out>) at ../include/pj/string.h:825
#2  pj_strcmp (str1=<optimized out>, str2=str2@entry=0x7fcf8055b798) at ../include/pj/string_i.h:172
#3  0x00007fcf94194d0d in find_transport_state_in_use (obj=0x555c79123830, arg=arg@entry=0x7fcf8055b780, flags=flags@entry=0)
    at res_pjsip.c:587
#4  0x0000555c77bae5ff in internal_ao2_traverse
    (self=self@entry=0x7fcf8402db80, flags=flags@entry=OBJ_SEARCH_NONE, cb_fn=cb_fn@entry=0x7fcf94194cb4 <find_transport_state_in_use>, arg=arg@entry=0x7fcf8055b780, tag=tag@entry=0x0, file=file@entry=0x7fcf941cd88d "res_pjsip.c", line=<optimized out>, func=<optimized out>, type=AO2_CALLBACK_DEFAULT, data=0x0) at astobj2_container.c:328
#5  0x0000555c77baea4f in __ao2_callback
    (c=c@entry=0x7fcf8402db80, flags=flags@entry=OBJ_SEARCH_NONE, cb_fn=cb_fn@entry=0x7fcf94194cb4 <find_transport_state_in_use>, arg=arg@entry=0x7fcf8055b780, tag=tag@entry=0x0, file=file@entry=0x7fcf941cd88d "res_pjsip.c", line=line@entry=602, func=func@entry=0x7fcf941ce9a0 <__PRETTY_FUNCTION__.95> "ast_sip_find_transport_state_in_use") at astobj2_container.c:414
#6  0x00007fcf941975e4 in ast_sip_find_transport_state_in_use (details=details@entry=0x7fcf8055b780) at res_pjsip.c:602
#7  0x00007fcf9400a926 in process_nat (tdata=0x7fcf840711e8) at res_pjsip_nat.c:335
#8  nat_on_tx_message (tdata=0x7fcf840711e8) at res_pjsip_nat.c:400
#9  0x00007fcfcf6a5548 in endpt_on_tx_msg (endpt=<optimized out>, tdata=0x7fcf840711e8) at ../src/pjsip/sip_endpoint.c:1124
#10 0x00007fcfcf6ad3eb in pjsip_transport_send
    (tr=0x555c792bef08, tdata=tdata@entry=0x7fcf840711e8, addr=addr@entry=0x7fcf98004364, addr_len=16, token=token@entry=0x7fcf98004288, cb=cb@entry=0x7fcfcf6bd684 <transport_callback>) at ../src/pjsip/sip_transport.c:935
#11 0x00007fcfcf6bd02e in tsx_send_msg (tsx=0x7fcf98004288, tdata=0x7fcf840711e8) at ../src/pjsip/sip_transaction.c:2243
#12 0x00007fcfcf6bf00c in tsx_on_state_proceeding_uas (tsx=0x7fcf98004288, event=<optimized out>) at ../src/pjsip/sip_transaction.c:2820
#13 0x00007fcfcf6c08ff in pjsip_tsx_send_msg (tsx=tsx@entry=0x7fcf98004288, tdata=tdata@entry=0x7fcf840711e8)
    at ../src/pjsip/sip_transaction.c:1864
#14 0x00007fcfcf6c31ef in pjsip_dlg_send_response (dlg=0x7fcfac039c68, tsx=0x7fcf98004288, tdata=tdata@entry=0x7fcf840711e8)
    at ../src/pjsip/sip_dialog.c:1603
#15 0x00007fcfcf685e86 in pjsip_inv_send_msg (inv=0x7fcf8403a0d8, tdata=tdata@entry=0x7fcf840711e8) at ../src/pjsip-ua/sip_inv.c:3528
#16 0x00007fcf94138c22 in ast_sip_session_send_response (session=0x7fcf84025fa0, tdata=0x7fcf840711e8) at res_pjsip_session.c:2578
#17 0x00007fcf9406ceda in answer (data=<optimized out>) at chan_pjsip.c:708
#18 0x00007fcf941950fe in sync_task (data=0x7fcfcc588110) at res_pjsip.c:2122
#19 0x0000555c77cef562 in ast_taskprocessor_execute (tps=tps@entry=0x555c79c339d0) at taskprocessor.c:1302
#20 0x0000555c77cf693d in execute_tasks (data=0x555c79c339d0) at threadpool.c:1350
#21 0x0000555c77cef562 in ast_taskprocessor_execute (tps=0x555c7918cc10) at taskprocessor.c:1302
#22 0x0000555c77cf73b1 in threadpool_execute (pool=0x555c7918c870) at threadpool.c:367
#23 worker_active (worker=0x7fcf6401b650) at threadpool.c:1137
#24 worker_start (arg=arg@entry=0x7fcf6401b650) at threadpool.c:1056
#25 0x0000555c77cfefa4 in dummy_start (data=<optimized out>) at utils.c:1607
#26 0x00007fcfcea87ac3 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#27 0x00007fcfceb19660 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by jcolp** [comment]
This appears to be the same fundamental issue as #509, if you can provide additional information there then please do so.
