### ISSUE TITLE
[bug]: Crash while executing MRCPRecog function call using AMI / AsynAGI

### ISSUE THREAD

**Issue by amitavhan** [asterisk/asterisk#769]
### Severity

Critical

### Versions

18.12.1

### Components/Modules

asyncagi, logger, unimrcp

### Operating Environment

Red Hat Enterprise Linux 8

### Frequency of Occurrence

Frequent

### Issue Description

Asterisk crash - general protection fault while executing UniMRCP MRCPRecog function.

**Core Dump Files**
[core-asterisk-2024-06-12T15-50-16Z-thread1.txt](https://github.com/user-attachments/files/15822206/core-asterisk-2024-06-12T15-50-16Z-thread1.txt)
[core-asterisk-2024-06-12T15-50-16Z-full.txt](https://github.com/user-attachments/files/15822207/core-asterisk-2024-06-12T15-50-16Z-full.txt)
[core-asterisk-2024-06-12T15-50-16Z-info.txt](https://github.com/user-attachments/files/15822208/core-asterisk-2024-06-12T15-50-16Z-info.txt)
[core-asterisk-2024-06-12T15-50-16Z-brief.txt](https://github.com/user-attachments/files/15822209/core-asterisk-2024-06-12T15-50-16Z-brief.txt)
[core-asterisk-2024-06-12T15-50-16Z-locks.txt](https://github.com/user-attachments/files/15822210/core-asterisk-2024-06-12T15-50-16Z-locks.txt)

### Relevant log output

```shell
Asterisk Full Log
[Jun 12 21:20:11] DEBUG[2239864] src/apt_poller_task.c: Wait for Messages [MRCPv2ConnectionAgent]
[Jun 12 21:20:11] DEBUG[2239864] src/apt_poller_task.c: Process Signalled Descriptor [MRCPv2ConnectionAgent]
[Jun 12 21:20:11] NOTICE[2239864] src/mrcp_client_connection.c: Receive MRCPv2 Data 172.17.137.248:42010 <-> 172.17.134.11:1544 [83 bytes]
MRCP/2.0 83 1 200 IN-PROGRESS
Channel-Identifier: 73d1206228d311ef@speechrecog


[Jun 12 21:20:11] DEBUG[2239864] src/apt_task.c: Signal Message to [MRCP Client] [0x7f037000fc40;2;3]
[Jun 12 21:20:11] DEBUG[2239864] src/apt_poller_task.c: Wait for Messages [MRCPv2ConnectionAgent]
[Jun 12 21:20:11] DEBUG[2239863] src/apt_task.c: Process Message [MRCP Client] [0x7f037000fc40;2;3]
[Jun 12 21:20:11] NOTICE[2239863] src/mrcp_client_session.c: Raise App MRCP Response ASR-283 <73d1206228d311ef>
[Jun 12 21:20:11] DEBUG[2239863] app_mrcprecog.c: (ASR-283) RECOGNIZE IN PROGRESS
[Jun 12 21:20:11] DEBUG[2239863] speech_channel.c: (ASR-283) READY ==> PROCESSING
[Jun 12 21:20:11] DEBUG[2239863] src/apt_consumer_task.c: Wait for Messages [MRCP Client]
[Jun 12 21:20:11] NOTICE[2242702][C-00000126] speech_channel.c: Stream file /var/lib/asterisk/sounds/1/33/Prompts/Hinselfservicebotmenu on PJSIP/anonymous-0000010f length:125310
[Jun 12 21:20:12] VERBOSE[2239946] manager.c: Manager 'acstpm' from 127.0.0.1, hanging up channel: PJSIP/anonymous-00000124
[Jun 12 21:20:12] VERBOSE[2242905][C-0000013d] pbx.c: Spawn extension (avhan, 8501, 2) exited non-zero on 'PJSIP/anonymous-00000124'
[Jun 12 21:20:12] VERBOSE[2239946] manager.c: Manager 'acstpm' from 127.0.0.1, hanging up channel: PJSIP/anonymous-00000125
[Jun 12 21:20:12] VERBOSE[2242906][C-0000013e] pbx.c: Spawn extension (avhan, 8501, 2) exited non-zero on 'PJSIP/anonymous-00000125'
[Jun 12 21:20:12] VERBOSE[2242928][C-00000140] res_agi.c: <PJSIP/anonymous-00000127> Playing '/var/lib/asterisk/sounds/1/33/Prompts/Engwelcome.slin' (escape_digits=) (sample_offset 0) (language 'en')
[Jun 12 21:20:14] VERBOSE[2242907][C-0000013f] pbx.c: Spawn extension (avhan, 8501, 2) exited non-zero on 'PJSIP/anonymous-00000126'
[Jun 12 21:20:14] VERBOSE[2239946] app_mixmonitor.c: MixMonitor close filestream (mixed)
[Jun 12 21:20:14] VERBOSE[2239946] manager.c: Manager 'acstpm' from 127.0.0.1, hanging up channel: PJSIP/default-0000008f
[Jun 12 21:20:14] VERBOSE[2241350] bridge_channel.c: Channel PJSIP/default-0000008f left 'simple_bridge' basic-bridge <d2febc62-661b-4968-85ee-c962ea85f413>
[Jun 12 21:20:14] VERBOSE[2241349] bridge_channel.c: Channel PJSIP/anonymous-00000052 left 'simple_bridge' basic-bridge <d2febc62-661b-4968-85ee-c962ea85f413>
[Jun 12 21:20:14] VERBOSE[2241353] app_mixmonitor.c: End MixMonitor Recording PJSIP/default-0000008f
[Jun 12 21:20:14] VERBOSE[2241349][C-00000142] pbx.c: Executing [100@avhan:3] AGI("PJSIP/anonymous-00000052", "agi:async") in new stack
[Jun 12 21:20:14] VERBOSE[2241349][C-00000142] pbx.c: Spawn extension (avhan, 100, 3) exited non-zero on 'PJSIP/anonymous-00000052'
[Jun 12 21:20:14] VERBOSE[2241349][C-00000142] pbx.c: Executing [100@avhan:3] AGI("PJSIP/anonymous-00000052", "agi:async") in new stack
[Jun 12 21:20:15] VERBOSE[2242970][C-00000143] pbx.c: Executing [8501@avhan:1] Ringing("PJSIP/anonymous-00000129", "1") in new stack
[Jun 12 21:20:15] VERBOSE[2242970][C-00000143] pbx.c: Executing [8501@avhan:2] AGI("PJSIP/anonymous-00000129", "agi:async") in new stack
[Jun 12 21:20:15] VERBOSE[2242971][C-00000144] pbx.c: Executing [8501@avhan:1] Ringing("PJSIP/anonymous-0000012a", "1") in new stack
[Jun 12 21:20:15] VERBOSE[2242971][C-00000144] pbx.c: Executing [8501@avhan:2] AGI("PJSIP/anonymous-0000012a", "agi:async") in new stack
[Jun 12 21:20:15] VERBOSE[2241349][C-00000142] res_agi.c: AGI Script Executing Application: (MRCPRecog) Options: (builtin:speech/transcribe, b=1&f=/var/lib/asterisk/sounds/1/39/Prompts/Hinrateus_1&spl=en-In&p=ums2&sw=true)
[Jun 12 21:20:15] NOTICE[2241349][C-00000142] app_mrcprecog.c: MRCPRecog() grammar: builtin:speech/transcribe
[Jun 12 21:20:15] NOTICE[2241349][C-00000142] app_mrcprecog.c: MRCPRecog() options: b=1&f=/var/lib/asterisk/sounds/1/39/Prompts/Hinrateus_1&spl=en-In&p=ums2&sw=true
[Jun 12 21:20:15] DEBUG[2241349][C-00000142] app_mrcprecog.c: Apply option b: 1
[Jun 12 21:20:15] DEBUG[2241349][C-00000142] app_mrcprecog.c: Apply option f: /var/lib/asterisk/sounds/1/39/Prompts/Hinrateus_1
[Jun 12 21:20:15] DEBUG[2241349][C-00000142] app_mrcprecog.c: Apply option spl: en-In
[Jun 12 21:20:15] DEBUG[2241349][C-00000142] app_mrcprecog.c: Apply option p: ums2
[Jun 12 21:20:15] DEBUG[2241349][C-00000142] app_mrcprecog.c: Apply option sw: true
[Jun 12 21:20:24] Asterisk 18.12.1 built by root @ IVRTELAPPSVR2-MIG on a x86_64 running Linux on 2024-04-25 21:57:20 UTC
[Jun 12 21:20:24] VERBOSE[2243138] message.c: Message handler 'dialplan' registered.
[Jun 12 21:20:24] VERBOSE[2243138] pbx_functions.c: Registered custom function 'MESSAGE'
[Jun 12 21:20:24] VERBOSE[2243138] pbx_functions.c: Registered custom function 'MESSAGE_DATA'

Linux Log
Jun 12 21:20:15 IVRTELAPPSVR2-MIG kernel: traps: asterisk[2241349] general protection fault ip:7f047906ae25 sp:7f033dc0cf88 error:0 in libc-2.28.so[7f0478f9f000+1bc000]
Jun 12 21:20:16 IVRTELAPPSVR2-MIG abrt-hook-ccpp[2242972]: Process 2239760 (asterisk) of user 0 killed by SIGSEGV - dumping core
Jun 12 21:20:22 IVRTELAPPSVR2-MIG dbus-daemon[1271]: [system] Activating service name='org.freedesktop.problems' requested by ':1.165838' (uid=0 pid=2243089 comm="/usr/libexec/platform-python /usr/bin/abrt-action-") (using servicehelper)
Jun 12 21:20:23 IVRTELAPPSVR2-MIG dbus-daemon[1271]: [system] Successfully activated service 'org.freedesktop.problems'
Jun 12 21:20:23 IVRTELAPPSVR2-MIG abrt-server[2243030]: Problem comes from unpackaged executable. Unable to create uReport.
Jun 12 21:20:23 IVRTELAPPSVR2-MIG abrt-server[2243030]: Cannot notify '/var/spool/abrt/ccpp-2024-06-12-21:20:16-2239760' via uReport: Event 'report_uReport' exited with 1

Core Dump
Thread 1 (Thread 0x7f033dc13700 (LWP 2241349)):
#0  0x00007f047906ae25 in __strlen_avx2 () from /lib64/libc.so.6
#1  0x00007f047900783d in vfprintf () from /lib64/libc.so.6
#2  0x00007f047902df64 in vsnprintf () from /lib64/libc.so.6
#3  0x00000000005c0d8b in __ast_str_helper (buf=0x7f033dc0d870, max_len=8192, append=0, fmt=0x7f040f7cbef0 "Ref entry %s from datastore on %sn", ap=0x7f033dc0da78, file=0x6b20c8 "asterisk/threadstorage.h", lineno=1006, function=0x6b3a08 "") at strings.c:71
#4  0x0000000000626f67 in ast_str_set_va (buf=0x7f033dc0d870, max_len=8192, fmt=0x7f040f7cbef0 "Ref entry %s from datastore on %sn", ap=0x7f033dc0da78) at /usr/local/src/asterisk-18.12.1/include/asterisk/strings.h:1002
#5  0x000000000062b6a4 in format_log_message_ap (level=0, sublevel=-1, file=0x7f040f7cbf39 "app_datastore.c", line=250, function=0x7f040f7cc0c0 <__FUNCTION__.19471> "app_datastore_session_add", callid=322, fmt=0x7f040f7cbef0 "Ref entry %s from datastore on %sn", ap=0x7f033dc0da78) at logger.c:1788
#6  0x000000000062cc74 in ast_log_full (level=0, sublevel=-1, file=0x7f040f7cbf39 "app_datastore.c", line=250, function=0x7f040f7cc0c0 <__FUNCTION__.19471> "app_datastore_session_add", callid=322, fmt=0x7f040f7cbef0 "Ref entry %s from datastore on %sn", ap=0x7f033dc0da78) at logger.c:2162
#7  0x000000000062cec3 in ast_log_ap (level=0, file=0x7f040f7cbf39 "app_datastore.c", line=250, function=0x7f040f7cc0c0 <__FUNCTION__.19471> "app_datastore_session_add", fmt=0x7f040f7cbef0 "Ref entry %s from datastore on %sn", ap=0x7f033dc0da78) at logger.c:2203
#8  0x000000000062ce39 in ast_log (level=0, file=0x7f040f7cbf39 "app_datastore.c", line=250, function=0x7f040f7cc0c0 <__FUNCTION__.19471> "app_datastore_session_add", fmt=0x7f040f7cbef0 "Ref entry %s from datastore on %sn") at logger.c:2192
#9  0x00007f040f7c045c in app_datastore_session_add (app_datastore=app_datastore@entry=0x7f0458007d88, entry=entry@entry=0x7f040f7cc874 "_default") at app_datastore.c:250
#10 0x00007f040f7c3af7 in app_recog_exec (chan=0x7f03d00eb480, data=<optimized out>) at app_mrcprecog.c:1140
#11 0x000000000054da03 in pbx_exec (c=0x7f03d00eb480, app=0x29adf40, data=0x7f03d00cfe5f "builtin:speech/transcribe, b=1&f=/var/lib/asterisk/sounds/1/39/Prompts/Hinrateus_1&spl=en-In&p=ums2&sw=true") at pbx_app.c:492
#12 0x00007f0409425a31 in handle_exec (chan=0x7f03d00eb480, agi=0x7f033dc0e500, argc=3, argv=0x7f033dc0e060) at res_agi.c:3136
#13 0x00007f04094285a7 in agi_handle_command (chan=0x7f03d00eb480, agi=0x7f033dc0e500, buf=0x7f03d00cfe50 "exec", dead=0) at res_agi.c:4044
#14 0x00007f0409421626 in launch_asyncagi (chan=0x7f03d00eb480, argc=1, argv=0x7f033dc0f408, efd=0x0) at res_agi.c:1883
#15 0x00007f04094224db in launch_script (chan=0x7f03d00eb480, script=0x7f033dc0f380 "agi:async", argc=1, argv=0x7f033dc0f408, fds=0x7f033dc0f810, efd=0x0, opid=0x7f033dc0f808) at res_agi.c:2205
#16 0x00007f040942a1b6 in agi_exec_full (chan=0x7f03d00eb480, data=0x7f033dc0f930 "agi:async", enhanced=0, dead=0) at res_agi.c:4513
#17 0x00007f040942a39b in agi_exec (chan=0x7f03d00eb480, data=0x7f033dc0f930 "agi:async") at res_agi.c:4556
#18 0x000000000054da03 in pbx_exec (c=0x7f03d00eb480, app=0x20e7f80, data=0x7f033dc0f930 "agi:async") at pbx_app.c:492
#19 0x0000000000539301 in pbx_extension_helper (c=0x7f03d00eb480, con=0x0, context=0x7f03d00ebe40 "mycontext", exten=0x7f03d00ebe90 "100", priority=3, label=0x0, callerid=0x7f03cc0f9350 "098xxxxx099", action=E_SPAWN, found=0x7f033dc12bcc, combined_find_spawn=1) at pbx.c:2938
#20 0x000000000053d242 in ast_spawn_extension (c=0x7f03d00eb480, context=0x7f03d00ebe40 "mycontext", exten=0x7f03d00ebe90 "100", priority=3, callerid=0x7f03cc0f9350 "098xxxxx099", found=0x7f033dc12bcc, combined_find_spawn=1) at pbx.c:4200
#21 0x000000000053def4 in __ast_pbx_run (c=0x7f03d00eb480, args=0x0) at pbx.c:4374
#22 0x000000000053f859 in ast_pbx_run_args (c=0x7f03d00eb480, args=0x0) at pbx.c:4739
#23 0x000000000053f883 in ast_pbx_run_args (c=0x53f883 <ast_pbx_run_args+136>, args=0x7f033dc12d00) at pbx.c:4746
#24 0x000000000048129f in ast_bridge_run_after_goto (chan=0x7f03d00eb480) at bridge_after.c:530
#25 0x0000000000475f0c in bridge_channel_ind_thread (data=0x7f03d00ea4c0) at bridge.c:1773
#26 0x00000000005d9bc8 in dummy_start (data=0x7f03d00b09a0) at utils.c:1572
#27 0x00007f0479ed31ca in start_thread () from /lib64/libpthread.so.0
#28 0x00007f0478fd8e73 in clone () from /lib64/libc.so.6
```

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by jcolp** [comment]
That module is not part of Asterisk. Any assistance with it should be undertaken from its source.

**Comment by agpatkar1** [comment]
> That module is not part of Asterisk. Any assistance with it should be undertaken from its source.

I understand it. Since crash is reported in Asterisk, I opened issue here. 
If you could take quick look at backtrace / core dump, it may help

**Comment by agpatkar1** [comment]
Thanks. Have raised issue with source package provider
