### ISSUE TITLE
[bug]: Asterisk crashes constantly and unexpectedly

### ISSUE THREAD

**Issue by lHumanizado** [asterisk/asterisk#899]
### Severity

Major

### Versions

21.3.1

### Components/Modules

ARI,Stasis,PJSIP

### Operating Environment

Amazonlinux 2023

### Frequency of Occurrence

Constant

### Issue Description

Im sorry if the title isnt right, its my first time opening an github issue and to be honest i dont know how else to call it because its exactly what happens, im running an asterisk server and i heavily use stasis and rest api to perform all the operations, i use **[channel/create](https://docs.asterisk.org/Latest_API/API_Documentation/Asterisk_REST_Interface/Channels_REST_API/#create)**  to create a channel, the stasis app listens for the StasisStart event and creates another channel, creates a bridge, bridge the channels together, etc, normal stuff. The problem is that when heavily used the asterisk containers start to crash, kubernetes restarts the container and its on again but this issue is constant, asterisk log says nothing, the last log i see on the server is the "Asterisk is ready" log.

I followed the steps on [https://docs.asterisk.org/Development/Debugging/Getting-a-Backtrace/](url) and collected this files:

[core-asterisk-2024-09-24T00-22-19Z-brief.txt](https://github.com/user-attachments/files/17106452/core-asterisk-2024-09-24T00-22-19Z-brief.txt)
[core-asterisk-2024-09-24T00-22-19Z-full.txt](https://github.com/user-attachments/files/17106453/core-asterisk-2024-09-24T00-22-19Z-full.txt)
[core-asterisk-2024-09-24T00-22-19Z-info.txt](https://github.com/user-attachments/files/17106454/core-asterisk-2024-09-24T00-22-19Z-info.txt)
[core-asterisk-2024-09-24T00-22-19Z-locks.txt](https://github.com/user-attachments/files/17106455/core-asterisk-2024-09-24T00-22-19Z-locks.txt)
[core-asterisk-2024-09-24T00-22-19Z-thread1.txt](https://github.com/user-attachments/files/17106456/core-asterisk-2024-09-24T00-22-19Z-thread1.txt)

I run gdb /path/to/asterisk /path/to/core/file

And got this:

```code
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000ffff8498c908 in refer_on_tx_request (tdata=0xffff1c4cdbf8) at res_pjsip_refer.c:1035
1035    res_pjsip_refer.c: No such file or directory.
```

My dockerfile is this:

```docker
FROM amazonlinux:2023

ENV ASTERISK_VER=21.3.1

WORKDIR /usr/src

RUN dnf groupinstall "Development Tools" -y
RUN dnf install -y \
  gdb \
  wget \
  cmake \
  redis6 \
  opus-devel \
  sqlite-devel \
  openssl-devel \
  libedit-devel \
  libuuid-devel \
  libxml2-devel \
  libxslt-devel

# Installs debug packages
RUN dnf debuginfo-install -y \
  zlib \
  glibc \
  libgcc \
  libedit \
  libuuid \
  libxml2 \
  libxslt \
  xz-libs \
  libstdc++ \
  libxcrypt \
  sqlite-libs \
  ncurses-libs \
  openssl-libs \
  systemd-libs

# Installs g729
RUN curl -Ls https://github.com/BelledonneCommunications/bcg729/archive/refs/tags/1.1.1.tar.gz -o bcg729.tar.gz &&\
  tar -xvf bcg729.tar.gz &&\
  cd bcg729-1.1.1 &&\
  cmake . -DCMAKE_INSTALL_PREFIX=/usr &&\
  make && make install &&\
  rm -R -f ../bcg729*

# Installs xmlstarlet (For g729 support)
RUN curl -Ls https://sourceforge.net/projects/xmlstar/files/xmlstarlet/1.6.1/xmlstarlet-1.6.1.tar.gz -o xmlstarlet.tar.gz &&\
  tar -xvf xmlstarlet.tar.gz &&\
  cd xmlstarlet-1.6.1 &&\
  ./configure &&\
  export C_INCLUDE_PATH=/usr/include/libxml2 &&\
  make && make install &&\
  rm -R -f ../xmlstarlet*

RUN curl -Ls https://github.com/asterisk/asterisk/releases/download/$ASTERISK_VER/asterisk-$ASTERISK_VER.tar.gz -o asterisk.tar.gz

RUN tar -xvf asterisk.tar.gz

WORKDIR /usr/src/asterisk-$ASTERISK_VER

RUN ./contrib/scripts/install_prereq install-unpackaged
RUN ./configure --with-pjproject-bundled --with-jansson-bundled

RUN make menuselect.makeopts

RUN menuselect/menuselect \
  --disable-category MENUSELECT_ADDONS \
  --disable-category MENUSELECT_CDR \
  --disable-category MENUSELECT_CEL \
  --disable-category MENUSELECT_CHANNELS \
  --disable-category MENUSELECT_CODECS \
  --disable-category MENUSELECT_FORMATS \
  --disable-category MENUSELECT_TESTS \
  --disable-category MENUSELECT_CFLAGS \
  --disable-category MENUSELECT_UTILS \
  --disable-category MENUSELECT_AGIS \
  --disable-category MENUSELECT_CORE_SOUNDS \
  --disable-category MENUSELECT_EXTRA_SOUNDS \
  --enable-category MENUSELECT_FUNCS \
  --enable-category MENUSELECT_RES \
  --disable res_digium_phone \
  --disable res_adsi \
  --disable res_smdi \
  --disable res_pjsip_geolocation \
  --disable app_voicemail \
  --disable app_amd \
  --disable app_queue \
  --disable app_confbridge \
  --disable app_adsiprog \
  --disable app_getcpeid \
  --enable chan_pjsip \
  --enable chan_audiosocket \
  --enable chan_bridge_media \
  --enable codec_ulaw \
  --enable codec_alaw \
  --enable format_wav \
  --enable format_pcm \
  --enable format_g729 \
  --enable codec_resample \
  --enable CORE-SOUNDS-EN-WAV \
  --enable CORE-SOUNDS-EN-ULAW \
  --enable CORE-SOUNDS-EN-ALAW \
  --enable CORE-SOUNDS-EN-G729 \
  --enable EXTRA-SOUNDS-EN-WAV \
  --enable EXTRA-SOUNDS-EN-ULAW \
  --enable EXTRA-SOUNDS-EN-ALAW \
  --enable EXTRA-SOUNDS-EN-G729 \
  --enable MOH-OPSOUND-WAV \
  --enable MOH-OPSOUND-ULAW \
  --enable MOH-OPSOUND-ALAW \
  --enable MOH-OPSOUND-G729 \
  --enable DONT_OPTIMIZE \
  --disable BUILD_NATIVE

RUN make
RUN make install
RUN make samples
RUN make config
RUN ldconfig

WORKDIR /usr/src

RUN rm -R -f asterisk*

COPY entrypoint.sh .
RUN chmod +x entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]
CMD [""]

```

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by jcolp** [comment]
Issues should be filed using the latest version of the specific Asterisk branch, such as the latest 21. A core debug would also be needed for this[1]. The description also doesn't appear to completely match what is going on, a not normal operation is going on - the sending of a REFER from Asterisk. It is important to be specific and complete when giving details about usage because things like that can make a difference.

[1] https://docs.asterisk.org/Operation/Logging/Collecting-Debug-Information/?h=collecting+debug

**Comment by lHumanizado** [comment]
Hi @jcolp Thank you for the response, i've past this days trying to provide more useful info about the issue, first of all let me sumarize what are the operations that are in place on the asterisk.

1. I have a cronjob that pulls calls and performs an HTTP request to the asterisk server using the ari **channel/create** endpoint
2. I have a websocket client registered to the asterisk box using stasis
3. When i receive the StasisStart event, i start the outbound call logic
4. The websocket client performs http request to the asterisk server to grab some information about the channel (audioformat from pjsip media and channelid for tracking porpuses)
5. Create a bridge
6. Place the call into the bridge
7. Perform dial
8. If the channel is answered i create an externalmedia channel and place it into the bridge, this is for an external api implementation
9. I also create another channel to call an agent, this agents are registered on another sip server, so i just Dial **PJSIP/default-endpoint/sip:number@host**, and place that channel into the bridge, i do the dial this way to avoid adding new siptrunks into the pjsip.conf files, i find it more easy this way
10. If the call is hung up at any point destroy the bridge and the created channels.

I created a isolated service to debug the issue better, until now the issue doesnt seem to be consistent, i monitored the server until two crashses, each time the gdb traceback returned different reasons for the crash, adding them to the list to the crash i posted on the first comment (as i listed on the septs before, there is no refer to my knowledge ocurring on the server)


Here is the first crash output after using gdb and running **bt full** (Dont know much about C, so i dont know if this useful or not, i think it may be)
```code
(gdb) bt full
#0  0x0000ffffb09a58a4 in pj_stricmp (str1=0x4d1, str2=0xffff6453b090) at ../include/pj/string_i.h:240
No locals.
#1  0x0000ffffb08ceef4 in pjsip_routing_hdr_print (hdr=0xfffea0249f60, 
    buf=0xffff421a25d2 "Route: <sip:someservice.some-long-namespace-name.svc.cluster.local:5060;lr>\r\nAllow: OPTIONS, REGISTER, SUBSCRIBE, NOTIFY, PUBLISH, INVITE, ACK, BYE, CANCEL, UPDATE, PRACK, INFO, MESSAGE, REFER\r\nk: 100rel, t"..., size=65189) at ../src/pjsip/sip_msg.c:1766
        st_hide = {ptr = 0xffffb09b83e0 "hide", slen = 4}
        printed = 0
        startbuf = 0xffff421a25d2 "Route: <sip:someservice.some-long-namespace-name.svc.cluster.local:5060;lr>\r\nAllow: OPTIONS, REGISTER, SUBSCRIBE, NOTIFY, PUBLISH, INVITE, ACK, BYE, CANCEL, UPDATE, PRACK, INFO, MESSAGE, REFER\r\nk: 100rel, t"...
        endbuf = 0xffff421b2477 ""
        pc = 0xffffb0a11430 <pconst>
        sip_uri = 0xffff34366440
        p = 0x4c1
#2  0x0000ffffb08cca48 in pjsip_hdr_print_on (hdr_ptr=0xfffea0249f60, 
    buf=0xffff421a25d2 "Route: <sip:someservice.some-long-namespace-name.svc.cluster.local:5060;lr>\r\nAllow: OPTIONS, REGISTER, SUBSCRIBE, NOTIFY, PUBLISH, INVITE, ACK, BYE, CANCEL, UPDATE, PRACK, INFO, MESSAGE, REFER\r\nk: 100rel, t"..., len=65189) at ../src/pjsip/sip_msg.c:628
        hdr = 0xfffea0249f60
#3  0x0000ffffb08cc530 in pjsip_msg_print (msg=0xfffea0249e10, 
    buf=0xffff421a2478 "INVITE sip:somenumber@x.x.x.x SIP/2.0\r\nv: SIP/2.0/UDP x.x.x.x:5060;rport;branch=z9hG4bKPj2f168a79-e9aa-4748-a3d2-42f527662235\r\nf: <sip:x.x.x.x>;tag=158ddb21-14a6-4bd1-8e8e-60a94"..., size=65535) at ../src/pjsip/sip_msg.c:504
        p = 0xffff421a25d2 "Route: <sip:someservice.some-long-namespace-name.svc.cluster.local:5060;lr>\r\nAllow: OPTIONS, REGISTER, SUBSCRIBE, NOTIFY, PUBLISH, INVITE, ACK, BYE, CANCEL, UPDATE, PRACK, INFO, MESSAGE, REFER\r\nk: 100rel, t"...
        end = 0xffff421b2477 ""
        len = 18
        hdr = 0xfffea0249f60
        clen_hdr = {ptr = 0xffffb09b8328 "l: ", slen = 3}
#4  0x0000ffffb08e0a98 in pjsip_tx_data_encode (tdata=0xffff41d927a8) at ../src/pjsip/sip_transport.c:615
        size = 281471769659440
#5  0x0000ffffb08e1518 in mod_on_tx_msg (tdata=0xffff41d927a8) at ../src/pjsip/sip_transport.c:898
No locals.
#6  0x0000ffffb08d9fac in endpt_on_tx_msg (endpt=0x1236fc18, tdata=0xffff41d927a8) at ../src/pjsip/sip_endpoint.c:1116
        status = 0
        mod = 0xffffb0a17690 <mod_msg_print>
--Type <RET> for more, q to quit, c to continue without paging--c
#7  0x0000ffffb08e166c in pjsip_transport_send (tr=0x127ee208, tdata=0xffff41d927a8, addr=0xffff41d92998, addr_len=16, token=0xfffea0152e58, cb=0xffffb08dc628 <stateless_send_transport_cb>) at ../src/pjsip/sip_transport.c:944
        status = 65535
#8  0x0000ffffb08dcb70 in stateless_send_transport_cb (token=0xfffea0152e58, tdata=0xffff41d927a8, sent=-70002) at ../src/pjsip/sip_util.c:1286
        status = 0
        cont = 1
        cur_addr = 0xffff41d92998
        cur_addr_type = PJSIP_TRANSPORT_UDP
        cur_addr_len = 16
        via = 0xfffea0249e80
        stateless_data = 0xfffea0152e58
        need_update_via = 1
#9  0x0000ffffb08dd00c in stateless_send_resolver_callback (status=0, token=0xfffea0152e58, addr=0xfffea04146d8) at ../src/pjsip/sip_util.c:1421
        stateless_data = 0xfffea0152e58
        tdata = 0xffff41d927a8
#10 0x0000ffff678c8600 in sip_resolve_invoke_user_callback (data=0xfffea04146b8) at res_pjsip/pjsip_resolver.c:206
        resolve = 0xfffea04146b8
        __FUNCTION__ = "sip_resolve_invoke_user_callback"
        __PRETTY_FUNCTION__ = "sip_resolve_invoke_user_callback"
#11 0x00000000005e5ea0 in ast_taskprocessor_execute (tps=0xffff34226468) at taskprocessor.c:1302
        local = {local_data = 0xffff6453b5a0, data = 0x5efb3c <execute_tasks+36>}
        t = 0xffff6800ade0
        size = 281471556412520
        __PRETTY_FUNCTION__ = "ast_taskprocessor_execute"
#12 0x00000000005efb48 in execute_tasks (data=0xffff34226468) at threadpool.c:1350
        tps = 0xffff34226468
#13 0x00000000005e5ea0 in ast_taskprocessor_execute (tps=0x1236c6a8) at taskprocessor.c:1302
        local = {local_data = 0xffff6453b610, data = 0x1236ac80}
        t = 0xffff680431c0
        size = 1683211452
        __PRETTY_FUNCTION__ = "ast_taskprocessor_execute"
#14 0x00000000005ed594 in threadpool_execute (pool=0x1236ac98) at threadpool.c:367
        __PRETTY_FUNCTION__ = "threadpool_execute"
#15 0x00000000005ef2dc in worker_active (worker=0xffff48000bd8) at threadpool.c:1137
        alive = 0
#16 0x00000000005ef068 in worker_start (arg=0xffff48000bd8) at threadpool.c:1056
        worker = 0xffff48000bd8
        saved_state = (ZOMBIE | DEAD | unknown: 0xfffc)
        __PRETTY_FUNCTION__ = "worker_start"
#17 0x00000000005faf90 in dummy_start (data=0x12368160) at utils.c:1607
        __cancel_buf = {__cancel_jmp_buf = {{__cancel_jmp_buf = {281472364954812, 281472399991936, 281472399991598, 281472399991599, 0, 281472364953760, 281472364384256, 0, 281473629974528, 281472364953760, 281472364951184, 13268811130960111318, 0, 13268931145701818142, 0, 0, 0, 0, 0, 0, 0, 0}, __mask_was_saved = 0}}, __pad = {0xffff6453b7d0, 0x0, 0x0, 0x0}}
        __cancel_routine = 0x463e4c <ast_unregister_thread>
        __cancel_arg = 0xffff6453c0a0
        __not_first_call = 0
        ret = 0xffff6453b8b0
        a = {start_routine = 0x5eefd4 <worker_start>, data = 0xffff48000bd8, name = 0xffff48000cf0 "worker_start         started at [ 1111] threadpool.c worker_thread_start()"}
        __PRETTY_FUNCTION__ = "dummy_start"
#18 0x0000ffffafa77834 in start_thread (arg=0xffff666a632f) at pthread_create.c:443
        ret = <optimized out>
        pd = 0xffff666a632f
        out = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {281472364953760, 281472399991936, 281472399991598, 281472399991599, 0, 281472364953760, 281472364384256, 0, 281473629974528, 281472364953760, 281472364951728, 13268931146954620690, 0, 13268931145701817934, 0, 0, 0, 0, 0, 0, 0, 0}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#19 0x0000ffffafa1be5c in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:79
```

As my understanding, the issue seems to be reading the Route header of one call.

This is the output for the second time it crashed:

```code
(gdb) bt full
#0  pjsip_uri_get_scheme (uri=0xfffe7c147ef0) at ../include/pjsip/sip_uri.h:260
No locals.
#1  0x0000ffff7ffeff2c in pjsip_name_addr_get_scheme (name=0xffff08c739a0) at ../src/pjsip/sip_uri.c:537
No locals.
#2  0x0000ffff668ca208 in pjsip_uri_get_scheme (uri=0xffff08c739a0) at /usr/src/asterisk-21.3.3/third-party/pjproject/source/pjsip/include/pjsip/sip_uri.h:260
No locals.
#3  0x0000ffff668ca3c4 in sips_contact_on_tx_request (tdata=0xffff08c726a8) at res_pjsip_sips_contact.c:67
        contact = 0xffff08c734b8
        route = 0xffff08c73960
        contact_uri = 0xffff08c73638
        __FUNCTION__ = "sips_contact_on_tx_request"
#4  0x0000ffff7fff1fac in endpt_on_tx_msg (endpt=0x2897a848, tdata=0xffff08c726a8) at ../src/pjsip/sip_endpoint.c:1116
        status = 0
        mod = 0xffff668fa060 <sips_contact_module>
#5  0x0000ffff7fff966c in pjsip_transport_send (tr=0x28891c08, tdata=0xffff08c726a8, addr=0xffff08c72898, addr_len=16, token=0xffff08070248, 
    cb=0xffff7fff4628 <stateless_send_transport_cb>) at ../src/pjsip/sip_transport.c:944
        status = 65535
#6  0x0000ffff7fff4b70 in stateless_send_transport_cb (token=0xffff08070248, tdata=0xffff08c726a8, sent=-70002) at ../src/pjsip/sip_util.c:1286
        status = 0
        cont = 1
        cur_addr = 0xffff08c72898
        cur_addr_type = PJSIP_TRANSPORT_UDP
        cur_addr_len = 16
--Type <RET> for more, q to quit, c to continue without paging--c
        via = 0xffff08c73880
        stateless_data = 0xffff08070248
        need_update_via = 1
#7  0x0000ffff7fff500c in stateless_send_resolver_callback (status=0, token=0xffff08070248, addr=0xffff081c9c98) at ../src/pjsip/sip_util.c:1421
        stateless_data = 0xffff08070248
        tdata = 0xffff08c726a8
#8  0x0000ffff66fe0600 in sip_resolve_invoke_user_callback (data=0xffff081c9c78) at res_pjsip/pjsip_resolver.c:206
        resolve = 0xffff081c9c78
        __FUNCTION__ = "sip_resolve_invoke_user_callback"
        __PRETTY_FUNCTION__ = "sip_resolve_invoke_user_callback"
#9  0x00000000005e5ea0 in ast_taskprocessor_execute (tps=0xfffe7c154ff8) at taskprocessor.c:1302
        local = {local_data = 0xffff646635a0, data = 0x5efb3c <execute_tasks+36>}
        t = 0xffff3804c9a0
        size = 281468468547576
        __PRETTY_FUNCTION__ = "ast_taskprocessor_execute"
#10 0x00000000005efb48 in execute_tasks (data=0xfffe7c154ff8) at threadpool.c:1350
        tps = 0xfffe7c154ff8
#11 0x00000000005e5ea0 in ast_taskprocessor_execute (tps=0x28977cc8) at taskprocessor.c:1302
        local = {local_data = 0xffff64663610, data = 0x28976640}
        t = 0xffff3804c9d0
        size = 1684423868
        __PRETTY_FUNCTION__ = "ast_taskprocessor_execute"
#12 0x00000000005ed594 in threadpool_execute (pool=0x28976658) at threadpool.c:367
        __PRETTY_FUNCTION__ = "threadpool_execute"
#13 0x00000000005ef2dc in worker_active (worker=0xffff10000bd8) at threadpool.c:1137
        alive = 0
#14 0x00000000005ef068 in worker_start (arg=0xffff10000bd8) at threadpool.c:1056
        worker = 0xffff10000bd8
        saved_state = (ZOMBIE | DEAD | unknown: 0xfffc)
        __PRETTY_FUNCTION__ = "worker_start"
#15 0x00000000005faf90 in dummy_start (data=0x289731d0) at utils.c:1607
        __cancel_buf = {__cancel_jmp_buf = {{__cancel_jmp_buf = {281472366167228, 281472390653056, 281472390652718, 281472390652719, 0, 281472366166176, 281472365596672, 0, 281472815329280, 281472366166176, 281472366163600, 6644967630206592409, 0, 6644873392649894993, 0, 0, 0, 0, 0, 0, 0, 0}, __mask_was_saved = 0}}, __pad = {0xffff646637d0, 0x0, 0x0, 0x0}}
        __cancel_routine = 0x463e4c <ast_unregister_thread>
        __cancel_arg = 0xffff646640a0
        __not_first_call = 0
        ret = 0xffff646638b0
        a = {start_routine = 0x5eefd4 <worker_start>, data = 0xffff10000bd8, name = 0xffff10000cf0 "worker_start         started at [ 1111] threadpool.c worker_thread_start()"}
        __PRETTY_FUNCTION__ = "dummy_start"
#16 0x0000ffff7f18f834 in start_thread (arg=0xffff65dbe32f) at pthread_create.c:443
        ret = <optimized out>
        pd = 0xffff65dbe32f
        out = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {281472366166176, 281472390653056, 281472390652718, 281472390652719, 0, 281472366166176, 281472365596672, 0, 281472815329280, 281472366166176, 281472366164144, 6644873393032772701, 0, 6644873392649895169, 0, 0, 0, 0, 0, 0, 0, 0}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#17 0x0000ffff7f133e5c in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:79
No locals.
```

Not pretty sure where the issue is in this one, i also did the steps you asked me and collected the debug information, here it is for the second crash:

[debug_log_899_00.txt](https://github.com/user-attachments/files/17171458/debug_log_899_00.txt)
[debug_log_899_01.txt](https://github.com/user-attachments/files/17171460/debug_log_899_01.txt)
[debug_log_899_02.txt](https://github.com/user-attachments/files/17171461/debug_log_899_02.txt)
[debug_log_899_03.txt](https://github.com/user-attachments/files/17171462/debug_log_899_03.txt)
[debug_log_899_04.txt](https://github.com/user-attachments/files/17171463/debug_log_899_04.txt)
[debug_log_899_05.txt](https://github.com/user-attachments/files/17171464/debug_log_899_05.txt)

The log is is splitted 25MB files bc of github filesize limit.

Also, dont know if is important but the specs that im using for the container is 2 CPU and 1GB RAM, also tried with 8 CPU and 16GB RAM, same result.

Please let me know if i can provide some more info to help to solve this issue

**Comment by escatg** [comment]
I have seen this type of crash, in my case it was due to slow DNS response, meaning that by the time stateless_send_transport_cb was finally called, the dialog for which the tdata was created was already destroyed because the transaction timeouted. Since some headers like Route are allocated on the pool of the dialog, the tdata becomes corrupted.

My solution was to switch to res_resolver_unbound instead of the system one that runs on one thread and is easily overloaded. That doesn't fix the underlying problem though and it is still easy to cause it by sending a lot of request while deliberately slowing down the DNS.

**Comment by bkford** [comment]
@lHumanizado this does look like it could be a potential memory corruption issue since all of the backtraces show different places where the crash occurs. It may be worth looking into @escatg solution for now and seeing if that fixes the problem. We can take a look at reproducing the issue given their comment, but things like this are usually very difficult to track down.

**Comment by lHumanizado** [comment]
Hi @bkford huge thanks to @escatg for the advice, to check the theory we removed the dns and put an static ip address and monitored during the last three days and the crash didnt happen again, also to double check we started to take a closer look to coredns and was indeed being overloaded during period of times where the crash happens, we are going to pursue a more definitive solution but seems that dns late response was the main issue.

We have another cluster running that keeps crashing, but this time the output is always about the REFER that i shared the first time, we dont do REFER on any way but this cluster only uses a single siptrunk so the problem may be something that this provider is doing we arent aware of, we are taking a closer to this.

Thanks to all for your advice and  help, if someone has any advice about the refer issue would be helpful too

**Comment by escatg** [comment]
Happy to help :) 

I wonder if the memory corruption caused here could be the trigger for [another problem](#168) that I reported, where some TLS packet suddenly gets corrupted and refused by the other end which cuts the connection.

Could some core dev check if my explanation for this crash in the previous message makes sense ? 

> it was due to slow DNS response, meaning that by the time stateless_send_transport_cb was finally called, the dialog for which the tdata was created was already destroyed because the transaction timeouted. Since some headers like Route are allocated on the pool of the dialog, the tdata becomes corrupted.

I captured that crash in valgrind:
```==531573== Thread 39:
==531573== Invalid read of size 8
==531573==    at 0x10550468: sips_contact_on_tx_request (res_pjsip_sips_contact.c:66)
==531573==    by 0x48E8C0B: endpt_on_tx_msg (sip_endpoint.c:1116)
==531573==    by 0x48F0CE2: pjsip_transport_send (sip_transport.c:936)
==531573==    by 0x48EBBB6: stateless_send_transport_cb (sip_util.c:1277)
==531573==    by 0x48EBF12: stateless_send_resolver_callback (sip_util.c:1378)
==531573==    by 0xFCE8CD1: sip_resolve_invoke_user_callback (pjsip_resolver.c:206)
==531573==    by 0x3092B8: ast_taskprocessor_execute (taskprocessor.c:1302)
==531573==    by 0x3136D9: execute_tasks (threadpool.c:1388)
==531573==    by 0x3092B8: ast_taskprocessor_execute (taskprocessor.c:1302)
==531573==    by 0x310E30: threadpool_execute (threadpool.c:368)
==531573==    by 0x312E4E: worker_active (threadpool.c:1175)
==531573==    by 0x312BB9: worker_start (threadpool.c:1094)
==531573==  Address 0xafc9008 is 40 bytes inside a block of size 512 free'd
==531573==    at 0x483CA3F: free (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==531573==    by 0x17E21F: __ast_free (astmm.c:1556)
==531573==    by 0x499FA34: default_block_free (pool_policy_malloc.c:78)
==531573==    by 0x49A8F28: reset_pool (pool.c:254)
==531573==    by 0x49A9028: pj_pool_reset (pool.c:276)
==531573==    by 0x49A99F2: cpool_release_pool (pool_caching.c:247)
==531573==    by 0x49A8888: pj_pool_release (pool_i.h:103)
==531573==    by 0x48E8254: pjsip_endpt_release_pool (sip_endpoint.c:691)
==531573==    by 0x490B917: dlg_on_destroy (sip_dialog.c:70)
==531573==    by 0x49A64BF: grp_lock_destroy (lock.c:398)
==531573==    by 0x49A6972: grp_lock_dec_ref (lock.c:563)
==531573==    by 0x49A69BA: pj_grp_lock_dec_ref (lock.c:654)
==531573==  Block was alloc'd at
==531573==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==531573==    by 0x17E1F6: __ast_repl_malloc (astmm.c:1551)
==531573==    by 0x499F9A2: default_block_alloc (pool_policy_malloc.c:46)
==531573==    by 0x49A89E5: pj_pool_create_block (pool.c:61)
==531573==    by 0x49A8C5F: pj_pool_allocate_find (pool.c:138)
==531573==    by 0x49A8781: pj_pool_alloc (pool_i.h:62)
==531573==    by 0x48E6C8D: pjsip_url_clone (sip_uri.c:525)
==531573==    by 0x48E57FC: pjsip_uri_clone (sip_uri.h:318)
==531573==    by 0x48E6FCE: pjsip_name_addr_assign (sip_uri.c:595)
==531573==    by 0x48DDF7A: pjsip_routing_hdr_clone (sip_msg.c:1806)
==531573==    by 0x48DB8AD: pjsip_hdr_clone (sip_msg.c:615)
==531573==    by 0x490D3BA: pjsip_dlg_set_route_set (sip_dialog.c:887)
```

I would like to try and fix it, but should we change pjsip which decrements the refcount on dialog while there is still tdata depending on it that is waiting to be sent ? Or would it be more on asterisk side to change, for example making sure that the data passed to the callback after DNS has no external dependency ?

**Comment by jcolp** [comment]
I can say that the hypothesis seems reasonable. As for fixing it, I think that can't be answered without first answering what happens in a normal PJSIP environment that doesn't have the Asterisk logic. Is it actually things we are doing, or does this still exist as an issue in PJSIP? Does it short circuit sending the tdata early so that nothing tries to access the invalid parts?
