### ISSUE TITLE
[bug]: pjporoject aborts in devmode when ICE is enabled but all interfaces are blacklisted

### ISSUE THREAD

**Issue by gtjoseph** [asterisk/asterisk#919]
### Severity

Minor

### Versions

all

### Components/Modules

pjproject

### Operating Environment

any

### Frequency of Occurrence

Frequent

### Issue Description

* Enable ICE in rtp.conf
* Blacklist all interfaces
* Forget to add [ice_host_candidates]
* Enable ICE on an endpoint
* Place a call to that endpoint
* Have the endpoint answer

If you're in devmode, pjproject causes asterisk to abort().
If you aren't in devmode, you get a few of these...
```
 WARNING[3398081][C-00000001]: res_rtp_asterisk.c:3347 __rtp_recvfrom: PJ ICE Rx error status code: 70004 'Invalid value or argument (PJ_EINVAL)'.
 WARNING[3398081][C-00000001]: res_rtp_asterisk.c:3347 __rtp_recvfrom: PJ ICE Rx error status code: 70004 'Invalid value or argument (PJ_EINVAL)'.
 WARNING[3398081][C-00000001]: res_rtp_asterisk.c:3347 __rtp_recvfrom: PJ ICE Rx error status code: 70004 'Invalid value or argument (PJ_EINVAL)'.
 WARNING[3398081][C-00000001]: res_rtp_asterisk.c:3347 __rtp_recvfrom: PJ ICE Rx error status code: 70004 'Invalid value or argument (PJ_EINVAL)'.
```

It's not a valid configuration but we should catch that at startup and give better error messages.

### Relevant log output

```shell
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007f6e858a86d3 in __pthread_kill_internal (threadid=<optimized out>, signo=6) at pthread_kill.c:78
#2  0x00007f6e8584fc4e in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007f6e85837902 in __GI_abort () at abort.c:79
#4  0x00007f6e8583781e in __assert_fail_base
    (fmt=0x7f6e859c3b98 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x7f6e869a0012 "!\"Invalid transport ID\"", file=file@entry=0x7f6e8699ee09 "../src/pjnath/ice_session.c", line=line@entry=3707, function=function@entry=0x7f6e869a02f0 <__PRETTY_FUNCTION__.0> "pj_ice_sess_on_rx_pkt")
    at assert.c:94
#5  0x00007f6e85847d87 in __assert_fail
    (assertion=0x7f6e869a0012 "!\"Invalid transport ID\"", file=0x7f6e8699ee09 "../src/pjnath/ice_session.c", line=3707, function=0x7f6e869a02f0 <__PRETTY_FUNCTION__.0> "pj_ice_sess_on_rx_pkt") at assert.c:103
#6  0x00007f6e868dc48f in pj_ice_sess_on_rx_pkt
    (ice=0x7f6d6c3eeee8, comp_id=2, transport_id=1, pkt=0x7f6e6d4851d0, pkt_size=74, src_addr=0x7f6e6d484fd0, src_addr_len=16)
    at ../src/pjnath/ice_session.c:3707
#7  0x00007f6e7ee9b54d in __rtp_recvfrom (instance=0x7f6d6c042450, buf=0x7f6e6d4851d0, size=8192, flags=0, sa=0x7f6e6d4871d0, rtcp=1)
    at res_rtp_asterisk.c:3337
#8  0x00007f6e7ee9b6fe in rtcp_recvfrom (instance=0x7f6d6c042450, buf=0x7f6e6d4851d0, size=8192, flags=0, sa=0x7f6e6d4871d0) at res_rtp_asterisk.c:3375
#9  0x00007f6e7eea918d in ast_rtcp_read (instance=0x7f6d6c042450) at res_rtp_asterisk.c:7111
#10 0x00007f6e7eead177 in ast_rtp_read (instance=0x7f6d6c042450, rtcp=1) at res_rtp_asterisk.c:8167
#11 0x000000000056ede3 in ast_rtp_instance_read (instance=0x7f6d6c042450, rtcp=1) at rtp_engine.c:605
#12 0x00007f6e7e47c589 in media_session_rtcp_read_callback (session=0x7f6d6c04ef60, session_media=0x7f6d6c040d58) at res_pjsip_sdp_rtp.c:2197
#13 0x00007f6e7e5e0208 in chan_pjsip_read_stream (ast=0x7f6c6c003a20) at chan_pjsip.c:857
#14 0x00000000004adcb3 in __ast_read (chan=0x7f6c6c003a20, dropaudio=0, dropnondefault=0) at channel.c:3770
#15 0x00000000004afa70 in ast_read_stream (chan=0x7f6c6c003a20) at channel.c:4283
#16 0x00000000004962c1 in bridge_handle_trip (bridge_channel=0x7f6c6c00e110) at bridge_channel.c:2549
#17 0x000000000049693d in bridge_channel_wait (bridge_channel=0x7f6c6c00e110) at bridge_channel.c:2762
#18 0x00000000004972c0 in bridge_channel_internal_join (bridge_channel=0x7f6c6c00e110) at bridge_channel.c:2938
#19 0x0000000000479e05 in bridge_channel_ind_thread (data=0x7f6c6c00e110) at bridge.c:1751
#20 0x00000000006027c5 in dummy_start (data=0x7f6c6c009bc0) at utils.c:1607
#21 0x00007f6e858a66d7 in start_thread (arg=<optimized out>) at pthread_create.c:447
#22 0x00007f6e8592a60c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
```

### Asterisk Issue Guidelines

- [X] Yes, I have read the Asterisk Issue Guidelines

**Comment by gtjoseph** [comment]
This is a dupplicate of #261
