### ISSUE TITLE
[improvement]: PJSIP support for Real Time Text

### ISSUE THREAD

**Issue by bnandaku** [asterisk/asterisk#997]
### Improvement Description

Enable PJSIP to support RTT with t140 and t140red codes

**Comment by nikolaciprich** [comment]
Hi, not sure if this is the right plase to report it, but I tried asterisk with this patch, but then it immediately crashes when call is initiated (before any RTT message is sent at all).
Here's full backtrace, if I can provide more info, please let me know:

(gdb) bt full
#0  0x00000000006028ea in ast_stream_get_position (stream=0x0) at stream.c:504
No locals.
#1  0x00000000004c1938 in ast_sendtext_data (chan=0x7fe678043c50, msg=0x7fe688010020) at channel.c:4840
        f = {frametype = AST_FRAME_TEXT, subclass = {integer = 0, {format = 0x2411e78, topology = 0x2411e78}, frame_ending = 0}, datalen = 3, samples = 0, mallocd = 2, mallocd_hdr_len = 0, 
          offset = 0, src = 0x77a9c2 "DIALPLAN", data = {ptr = 0x0, uint32 = 0, pad = "\000\000\000\000\000\000\000"}, delivery = {tv_sec = 0, tv_usec = 0}, frame_list = {next = 0x0}, 
          flags = 0, ts = 0, len = 0, seqno = 0, stream_num = 0}
        body_len = 3
        res = 0
        body = 0x7fe68801003c "﻿"
        content_type = 0x792ddc ""
        __PRETTY_FUNCTION__ = "ast_sendtext_data"
        __FUNCTION__ = "ast_sendtext_data"
#2  0x00000000004c1e43 in ast_sendtext (chan=0x7fe678043c50, text=0x7fe688000b90 "﻿") at channel.c:4891
        msg = 0x7fe688010020
        rc = 2346
        attrs = {{type = AST_MSG_DATA_ATTR_BODY, value = 0x7fe688000b90 "﻿"}}
        __PRETTY_FUNCTION__ = "ast_sendtext"
#3  0x00000000004a39d1 in sendtext_safe (chan=0x7fe678043c50, f=0x7fe678053940) at bridge_channel.c:2352
        text = 0x7fe688000b90 "﻿"
        __PRETTY_FUNCTION__ = "sendtext_safe"
#4  0x00000000004a3dcd in bridge_channel_handle_write (bridge_channel=0x7fe678015460) at bridge_channel.c:2437
        fr = 0x7fe678053940
        sync_payload = 0x49cbfe <_ast_bridge_channel_unlock+57>
        num = 0
        msg = 0x7fe69f694bf0
        __PRETTY_FUNCTION__ = "bridge_channel_handle_write"
        __FUNCTION__ = "bridge_channel_handle_write"
#5  0x00000000004a48f9 in bridge_channel_wait (bridge_channel=0x7fe678015460) at bridge_channel.c:2782
        ms = -1
        outfd = 39
        chan = 0x0
        __PRETTY_FUNCTION__ = "bridge_channel_wait"
        __FUNCTION__ = "bridge_channel_wait"
#6  0x00000000004a5372 in bridge_channel_internal_join (bridge_channel=0x7fe678015460) at bridge_channel.c:2947
        res = 0
        indicate_src_change = 1 '\001'
        channel_features = 0x0
        peer = 0x0
        swap = 0x0
        __FUNCTION__ = "bridge_channel_internal_join"
        __PRETTY_FUNCTION__ = "bridge_channel_internal_join"
#7  0x0000000000484fe9 in bridge_channel_ind_thread (data=0x7fe678015460) at bridge.c:1751
        bridge_channel = 0x7fe678015460
        chan = 0x7fe688000950
        __PRETTY_FUNCTION__ = "bridge_channel_ind_thread"
#8  0x0000000000623c45 in dummy_start (data=0x7fe6780126e0) at utils.c:1607
        __clframe = {__cancel_routine = 0x4604c4 <ast_unregister_thread>, __cancel_arg = 0x7fe69f695700, __do_it = 1, __cancel_type = 0}
        ret = 0x7d000
        a = {start_routine = 0x484faa <bridge_channel_ind_thread>, data = 0x7fe678015460, 
          name = 0x7fe6780127a0 "bridge_channel_ind_thread started at [ 1845] bridge.c bridge_impart_internal()"}
        __PRETTY_FUNCTION__ = "dummy_start"
#9  0x00007fe6a37e7ea5 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#10 0x00007fe6a17aeb0d in clone () from /lib64/libc.so.6

**Comment by henningw** [comment]
@nikolaciprich We provided a new version of this patch (#1128). It would be great if you could give this a try. If you encounter any issues, please report back in the mentioned PR.

**Comment by henningw** [comment]
We provided a new version of this patch (https://github.com/asterisk/asterisk/pull/1128). It would be great if you could give this a try. If you encounter any issues, please report back in the mentioned PR.
